/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import java.lang.reflect.Proxy;

public class AppImpl implements App {
    @Override
    public String getGreeting() {
        return getGreeting0();
    }

    private String getGreeting0() {
        return "Hello, World!";
    }

    public static void main(String[] args) {
        App app = (App) Proxy.newProxyInstance(AppImpl.class.getClassLoader(), new Class[] { App.class }, new Delegator());
        System.out.println(app.getGreeting());
    }
}